# Generated by Django 6.0.5 on 2026-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='stage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
