# Generated by Django 6.0.5 on 2026-06-19 05:31

from django.db import migrations


def create_enemies(apps, schema_editor):
    Enemy = apps.get_model("game", "Enemy")
    Enemy.objects.bulk_create(
        [
            # Act 1 일반몹 (stage 1~3)
            Enemy(name="슬라임", hp=8, stage=1, dice_min=1, dice_max=3, act=1, is_boss=False),
            Enemy(name="고블린", hp=15, stage=2, dice_min=2, dice_max=4, act=1, is_boss=False),
            Enemy(name="오크", hp=25, stage=3, dice_min=3, dice_max=5, act=1, is_boss=False),
            # Act 1 보스 (stage 4, 둘 중 랜덤)
            Enemy(name="오크 군주", hp=40, stage=4, dice_min=3, dice_max=6, act=1, is_boss=True),
            Enemy(name="동굴 트롤", hp=50, stage=4, dice_min=4, dice_max=6, act=1, is_boss=True),
        ]
    )


def delete_enemies(apps, schema_editor):
    Enemy = apps.get_model("game", "Enemy")
    Enemy.objects.filter(act=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_enemy_stage'),
    ]

    operations = [
        migrations.RunPython(create_enemies, delete_enemies),
    ]
