# Generated by Django 6.0.5 on 2026-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_seed_dummy_enemies'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
