# Generated by Django 6.0.5 on 2026-06-19 09:29

from django.db import migrations


def create_skills(apps, schema_editor):
    Skill = apps.get_model("game", "Skill")
    Skill.objects.create(
        code="critical",
        name="크리티컬",
        description="공격 시 일정 확률로 데미지가 2배가 됩니다. 레벨당 확률 10% 증가.",
        max_level=3,
        effect_per_level=0.1,
    )


def delete_skills(apps, schema_editor):
    Skill = apps.get_model("game", "Skill")
    Skill.objects.filter(code="critical").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_skill_code'),
    ]

    operations = [
        migrations.RunPython(create_skills, delete_skills),
    ]
