# Generated by Django 6.0.5 on 2026-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_seed_critical_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
