# Generated by Django 6.0.5 on 2026-06-20 16:09

from django.db import migrations


def reseed_enemies(apps, schema_editor):
    Enemy = apps.get_model("game", "Enemy")
    # 기존 Act 1 더미 적을 지우고 이미지가 있는 새 적으로 교체
    Enemy.objects.filter(act=1).delete()
    Enemy.objects.bulk_create(
        [
            # Act 1 일반몹 (stage 1~3) - 뒤로 갈수록 주사위가 강해짐
            Enemy(name="쥐", hp=8, stage=1, dice_min=1, dice_max=3, act=1, is_boss=False, image="game/enemies/mouse.png"),
            Enemy(name="벌", hp=15, stage=2, dice_min=2, dice_max=5, act=1, is_boss=False, image="game/enemies/bee.png"),
            Enemy(name="슬라임", hp=25, stage=3, dice_min=3, dice_max=6, act=1, is_boss=False, image="game/enemies/slime.png"),
            # Act 1 보스 (stage 4, 둘 중 랜덤) - 일반몹보다 확실히 강한 주사위
            Enemy(name="해골", hp=40, stage=4, dice_min=5, dice_max=9, act=1, is_boss=True, image="game/enemies/skeleton.png"),
            Enemy(name="데빌", hp=50, stage=4, dice_min=6, dice_max=11, act=1, is_boss=True, image="game/enemies/devil.png"),
        ]
    )


def reverse_reseed(apps, schema_editor):
    Enemy = apps.get_model("game", "Enemy")
    Enemy.objects.filter(act=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_enemy_image'),
    ]

    operations = [
        migrations.RunPython(reseed_enemies, reverse_reseed),
    ]
