# Generated by Django 6.0.5 on 2026-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_reseed_act1_enemies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=50),
        ),
    ]
