# Generated by Django 6.0.5 on 2026-06-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rebalance_all_acts'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
