# Generated by Django 6.0.5 on 2026-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_reseed_enemies_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='crit_chance',
            field=models.FloatField(default=0),
        ),
    ]
